### ISSUE TITLE
there are error in this line , when you go to source says to you : 'setOperational' was not declared in this scope

### ISSUE THREAD

**Issue by ameer2013** [Blackstaff/wsn_routing#1]
there are error in this line , when you go to source says to you : 'setOperational' was not declared in this scope

![screenshot   @#14](https://user-images.githubusercontent.com/32545103/31230978-3a33af2a-a9ee-11e7-836b-6bc59c0ff564.png)
https://github.com/Blackstaff/wsn_routing/blob/3d7fbbb990dba9a21fb0e05a327ed55f8f658d9c/src/common/sensor/WSNSensorApp.cc#L67

**Comment by ameer2013** [comment]
there are error in this line , when you go to source says to you : 'setOperational' was not declared in this scope

**Comment by Blackstaff** [comment]
Are you using Inet with my changes added to it (point 2 of my instruction)? I've changed the parent of IPvXTrafGen to ApplicationBase. The 'setOperational' method is inherited from OperationalBase through IPvXTrafGen -> ApplicationBase.
The wsn_routing code should be used along with the modified Inet 3.5 framework.

**Comment by ameer2013** [comment]
I used inet 3.5 but i downloaded from inet company , can you send me the
modified inet 3.5 ? Please..please

بتاريخ ٢٠١٧/١٠/٠٦ ٥:٥٠ م، كتب "Mateusz Czarnecki" <notifications@github.com

**Comment by Blackstaff** [comment]
Sure, you just need to use this command:

`git clone -b wsn_routing_fixes --single-branch https://github.com/Blackstaff/inet.git inet`

**Comment by ameer2013** [comment]
my dear ..
Can you explain me in a simplified way about the second step?
I have taken the following steps:
First erected omnet++ v3.5.1
Second, I import wsn_routing to workspace.
Third, I import inet v3.5 to the same workspace.
But I got the mistake I sent you ..
I am sorry for the linguistic expression because I am weak in English ...
with my greetings


بتاريخ ٢٠١٧/١٠/٠٦ ٦:٠٥ م، كتب "Mateusz Czarnecki" <notifications@github.com
>:

Sure, you just need to use this command:

git clone -b wsn_routing_fixes --single-branch
https://github.com/Blackstaff/inet.git inet

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Blackstaff/wsn_routing/issues/1#issuecomment-334781672>,
or mute the thread

**Comment by Blackstaff** [comment]
You need:
1. Omnet++ v5.1
2. wsn_routing
3. Inet 3.5 from a branch called 'wsn_routing_fixes', which you can find here:

https://github.com/Blackstaff/inet/tree/wsn_routing_fixes

**Comment by ameer2013** [comment]
Thank you very very much ...

بتاريخ ٢٠١٧/١٠/٠٦ ٦:٣٧ م، كتب "Mateusz Czarnecki" <notifications@github.com

**Comment by ameer2013** [comment]
Sorry dear for the inconvenience ... but there is no download button for
inet..


بتاريخ ٢٠١٧/١٠/٠٦ ٦:٣٧ م، كتب "Mateusz Czarnecki" <notifications@github.com

**Comment by Blackstaff** [comment]
How about this https://github.com/Blackstaff/inet/archive/wsn_routing_fixes.zip ?

**Comment by ameer2013** [comment]
Thank you very very very  much ...

بتاريخ ٢٠١٧/١٠/٠٦ ٦:٤٧ م، كتب "Mateusz Czarnecki" <notifications@github.com

**Comment by Blackstaff** [comment]
You're welcome :-)
